services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      - CONFIG_PATH=~/config/authelia
    volumes:
      - type: bind
        source: ~/config/authelia
        target: /config
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.local.solivan.dev`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.local.solivan.dev'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: always
    healthcheck:
      disable: true
networks:
  proxy:
    external: true
