# SOPS configuration for managing secrets across NixOS and home-manager systems
# 
# Keys:
# - danny_personal: Your personal age key (converted from SSH id_sdev)
# - tidus_host: NixOS laptop host key
# - aerith_host: NixOS server host key (you'll need to add this later)
# - macOS hosts will use danny_personal key via home-manager

keys:
  - &danny_personal age1a6p0xdsk0z9h6r4l43nfc63mwaukfju7cljhgvqd2wxc0ukves9swqlvfn
  - &tidus_host age10hp8ww0e84mdfwx0fhhmzhvdn6cayrpk0k32jdxauwap87rvrdgsrj50lg
  # Add more host keys here as needed:
  # - &aerith_host age1...
  # - &waver_host age1...

creation_rules:
  # NixOS system secrets (common to all NixOS hosts)
  - path_regex: systems/nixos/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danny_personal
      - *tidus_host
      # Add other hosts here as you set them up

  # NixOS module secrets (shared across all NixOS hosts)
  - path_regex: modules/nixos/security/sops/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danny_personal
  
  # User home secrets (SSH keys, personal tokens)
  - path_regex: home/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danny_personal
      - *tidus_host  # Hosts need to decrypt user secrets too
  
  # Host-specific secrets (if needed later)
  - path_regex: hosts/.*/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *danny_personal
      - *tidus_host
  
