services:
  calibre-web:
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - DOCKER_MODS=ghcr.io/linuxserver/mods:universal-calibre
      - TZ=America/Los_Angeles
      - CONFIG_PATH=~/config/calibre-web
      - LIBRARY_PATH=~/config/calibre
      - PGID=0
      - PUID=0
      - MOUNT_PATH=/mnt/titan
    image: linuxserver/calibre-web:latest
    volumes:
      - type: bind
        source: ~/config/calibre-web
        target: /config
      - type: bind
        source: ~/config/calibre
        target: /books
      - type: bind
        source: /mnt/titan
        target: /root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.entrypoints=http"
      - "traefik.http.routers.calibre-web.rule=Host(`books.local.solivan.dev`)"
      - "traefik.http.middlewares.calibre-web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.calibre-web.middlewares=calibre-web-https-redirect"
      - "traefik.http.routers.calibre-web-secure.entrypoints=https"
      - "traefik.http.routers.calibre-web-secure.rule=Host(`books.local.solivan.dev`)"
      - "traefik.http.routers.calibre-web-secure.tls=true"
      - "traefik.http.routers.calibre-web-secure.service=calibre-web"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: false

networks:
  proxy:
    external: true
