# Docker Compose file for the complete Nextcloud office stack
# Usage: docker compose up -d

services:
  # Nextcloud Database
  nextcloud-db:
    image: mariadb:lts
    container_name: nextcloud-db
    restart: always
    networks:
      - proxy
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ~/config/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}

  # Nextcloud Redis
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - proxy

  # Nextcloud App
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.local.solivan.dev`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.local.solivan.dev`) || Host(`nextcloud.solivan.dev`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - nextcloud-redis
      - nextcloud-db
    volumes:
      - ~/config/nextcloud/library:/var/www/html
    environment:
      # Database configuration
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PORT=6379
      # Trusted domains for access
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud.local.solivan.dev nextcloud.solivan.dev
      - NEXTCLOUD_DEFAULT_PHONE_REGION=US
      # Reverse proxy configuration
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nextcloud.local.solivan.dev
      - OVERWRITEHOST=nextcloud.local.solivan.dev
      - TRUSTED_PROXIES=172.16.0.0/12


  # OnlyOffice Document Server
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    networks:
      - proxy
    environment:
      # Security settings
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - USE_UNAUTHORIZED_STORAGE=true
      # WOPI settings for Nextcloud
      - WOPI_ENABLED=true
      # Allow connections from Nextcloud
      - ALLOW_META_IP_ADDRESS=true
      - ALLOW_PRIVATE_IP_ADDRESS=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.entrypoints=http"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.local.solivan.dev`)"
      - "traefik.http.middlewares.onlyoffice-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-https-redirect"
      - "traefik.http.routers.onlyoffice-secure.entrypoints=https"
      - "traefik.http.routers.onlyoffice-secure.rule=Host(`onlyoffice.local.solivan.dev`)"
      - "traefik.http.routers.onlyoffice-secure.tls=true"
      - "traefik.http.routers.onlyoffice-secure.service=onlyoffice"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      - "traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice-secure.middlewares=onlyoffice-headers"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - nextcloud

networks:
  proxy:
    external: true