name: Sync to GitHub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote add github https://${{ secrets.GH_TOKEN }}@github.com/nightconcept/dotfiles-nix.git
          git push github main --force
