name: Sync to GitHub

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FORGEJO_TOKEN }}

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add github https://${{ secrets.GITHUB_TOKEN }}@github.com/nightconcept/dotfiles-nix.git
          git push github main --force
