version: '3'

services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:1-alpine
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.entrypoints=http"
      - "traefik.http.routers.uptimekuma.rule=Host(`${DOMAIN}`)"
      - "traefik.http.middlewares.uptimekuma-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.uptimekuma.middlewares=uptimekuma-https-redirect"
      - "traefik.http.routers.uptimekuma-secure.entrypoints=https"
      - "traefik.http.routers.uptimekuma-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.uptimekuma-secure.tls=true"
      - "traefik.http.routers.uptimekuma-secure.service=uptimekuma"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: false

networks:
  proxy:
    external: true
