services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:14
    networks:
      - proxy
    ports:
      - target: 51820
        published: "51820"
        protocol: udp
    restart: always
    environment:
      - WG_HOST=terra.nightconcept.net
      - WG_DEFAULT_DNS=cyan.nclabs.net
      - WG_PORT=51820
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
    volumes:
      - type: bind
        source: ~/config/wg-easy
        target: /etc/wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.entrypoints=http"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.local.solivan.dev`)"
      - "traefik.http.middlewares.wireguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wireguard.middlewares=wireguard-https-redirect"
      - "traefik.http.routers.wireguard-secure.entrypoints=https"
      - "traefik.http.routers.wireguard-secure.rule=Host(`wireguard.local.solivan.dev`)"
      - "traefik.http.routers.wireguard-secure.tls=true"
      - "traefik.http.routers.wireguard-secure.service=wireguard"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.docker.network=proxy"
    privileged: false

networks:
  proxy:
    external: true
