services:
  enshrouded:
    image: mornedhels/enshrouded-server:latest
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    network_mode: "host"
    stop_grace_period: 90s
    ports:
      - "15636-15637:15636-15637/udp"
    volumes:
      - type: bind
        source: '$CONFIG_PATH'
        target: /opt/enshrouded
    environment:
      - SERVER_NAME=New World 1
      - SERVER_SLOT_COUNT=8
      - SERVER_SAVE_DIR=./savegame
      - UPDATE_CRON=*/30 * * * *
      - BACKUP_CRON=0 * * * *
      - BACKUP_DIR=./backup
      - BACKUP_MAX_COUNT=72
      - SERVER_ROLE_0_NAME=Admins
      - SERVER_ROLE_0_PASSWORD=giraffe
      - SERVER_ROLE_0_CAN_KICK_BAN=true
      - SERVER_ROLE_0_CAN_ACCESS_INVENTORIES=true
      - SERVER_ROLE_0_CAN_EDIT_BASE=true
      - SERVER_ROLE_0_CAN_EXTEND_BASE=true
      - SERVER_ROLE_0_RESERVED_SLOTS=1
      - SERVER_ROLE_1_NAME=Players
      - SERVER_ROLE_1_PASSWORD=money
      - SERVER_ROLE_1_CAN_KICK_BAN=false
      - SERVER_ROLE_1_CAN_ACCESS_INVENTORIES=false
      - SERVER_ROLE_1_CAN_EDIT_BASE=false
      - SERVER_ROLE_1_CAN_EXTEND_BASE=false
      - SERVER_ROLE_1_RESERVED_SLOTS=4
