---
services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - proxy
    restart: unless-stopped
    ports:
     - 8087:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ronweasel.nclabs.net:11434
     - PUID=1000
     - PGID=1000
     - TZ=America/Los_Angeles
    volumes:
      - /var/opt/data/ollama/webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai.entrypoints=http"
      - "traefik.http.routers.ai.rule=Host(`ai.local.solivan.dev`)"
      - "traefik.http.middlewares.ai-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ai.middlewares=ai-https-redirect"
      - "traefik.http.routers.ai-secure.entrypoints=https"
      - "traefik.http.routers.ai-secure.rule=Host(`ai.local.solivan.dev`)"
      - "traefik.http.routers.ai-secure.tls=true"
      - "traefik.http.routers.ai-secure.service=ai"
      - "traefik.http.services.ai.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: false

networks:
  proxy:
    external: true
