http:
#region routers 
  routers:
    pihole-primary:
      entryPoints:
        - "https"
      rule: "Host(`pihole-primary.local.solivan.dev`)"
      middlewares:
        - redirectregex-pihole
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole-primary

    plex:
      entryPoints:
        - "https"
      rule: "Host(`plex.local.solivan.dev`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: plex

    # Expose a ping endpoint, for healthcheck services to check traefik is still up.
    ping:
      rule: "(Host(`localhost`) || Host(`traefik-dashboard.local.solivan.dev`)) && PathPrefix(`/ping`)"
      service: "ping@internal"
      tls: {}
      entryPoints:
        - ping
#endregion

#region services
  services:
    pihole-primary:
      loadBalancer:
        servers:
          - url: "http://192.168.1.101:80"
        passHostHeader: true

    plex:
      loadBalancer:
        servers:
          - url: "https://192.168.1.111:32400"
        passHostHeader: true
#endregion

#region middlewares
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
#end region