services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - CRON_MIN=${CRON_MIN}
      - FRESHRSS_ENV=production
      - BASE_URL=${BASE_URL}
    ports:
      - "${PORT}:80"
    volumes:
      - ${DATA_PATH}:/var/www/FreshRSS/data
      - ${EXTENSIONS_PATH}:/var/www/FreshRSS/extensions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freshrss.entrypoints=http"
      - "traefik.http.routers.freshrss.rule=Host(`freshrss.local.solivan.dev`)"
      - "traefik.http.middlewares.freshrss-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.freshrss.middlewares=freshrss-https-redirect"
      - "traefik.http.routers.freshrss-secure.entrypoints=https"
      - "traefik.http.routers.freshrss-secure.rule=Host(`freshrss.local.solivan.dev`)"
      - "traefik.http.routers.freshrss-secure.tls=true"
      - "traefik.http.routers.freshrss-secure.service=freshrss"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}"

networks:
  proxy:
    external: true