services:
  radarr:
    container_name: radarr
    restart: always
    networks:
      - proxy
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    image: linuxserver/radarr:latest
    ports:
      - target: 7878
        published: "7878"
        protocol: tcp
    volumes:
      - type: bind
        source: ${CONFIG_PATH}
        target: /config
      - type: bind
        source: ${DOWNLOADS_PATH}
        target: /downloads
      - type: bind
        source: ${DOWNLOADS_PATH}
        target: /mnt/titan/downloads
      - type: bind
        source: ${MOVIES_PATH}
        target: /movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.solivan.dev`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.local.solivan.dev`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"
      - 'traefik.http.routers.radarr-secure.middlewares=authelia@docker'
    privileged: false

networks:
  proxy:
    external: true
