services:
  knot:
    image: hqnna/knot:${IMAGE_TAG}
    container_name: knot
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - KNOT_SERVER_HOSTNAME=${KNOT_SERVER_HOSTNAME}
      - KNOT_SERVER_OWNER=${KNOT_SERVER_OWNER}
      - KNOT_SERVER_PORT=${KNOT_SERVER_PORT}
      - KNOT_SERVER_SECRET=${KNOT_SERVER_SECRET}
    ports:
      - "${SSH_PORT}:2222"  # SSH port for git operations
      - "${HTTP_PORT}:8080" # HTTP port for web interface
    volumes:
      - ${DATA_PATH}:/data
      - ${CONFIG_PATH}:/config
    labels:
      - "traefik.enable=true"
      # HTTP redirect to HTTPS
      - "traefik.http.routers.knot.entrypoints=http"
      - "traefik.http.routers.knot.rule=Host(`knot.local.solivan.dev`) || Host(`knot.solivan.dev`)"
      - "traefik.http.middlewares.knot-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.knot.middlewares=knot-https-redirect"
      # HTTPS configuration
      - "traefik.http.routers.knot-secure.entrypoints=https"
      - "traefik.http.routers.knot-secure.rule=Host(`knot.local.solivan.dev`) || Host(`knot.solivan.dev`)"
      - "traefik.http.routers.knot-secure.tls=true"
      - "traefik.http.routers.knot-secure.service=knot"
      - "traefik.http.services.knot.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}"

networks:
  proxy:
    external: true