"$schema" = "https://starship.rs/config-schema.json"

# Format with box drawing characters and gradient blocks - matches P10k style
format = "[╭─](#6c6c6c)[](fg:#444444)$os$username$hostname[ ](fg:#6c6c6c bg:#444444)$directory$git_branch$git_status[](fg:#444444)$fill[](fg:#444444)$nix_shell$time[](fg:#444444)[─╮ ](#6c6c6c)$line_break[╰─ ](#6c6c6c)$character"

# Right prompt format
right_format = "[─╯ ](#6c6c6c)$line_break"

# Color reference
[palettes.p10k_classic]
red = "#d70000"           # 160
orange = "#d78700"        # 172
yellow = "#d7af00"        # 178
light_yellow = "#afaf87"  # 144
green = "#5fd700"         # 76 (git branch in P10k)
teal = "#5fd7d7"          # 80
light_teal = "#87d7d7"    # 116
cyan = "#00afff"          # 39 (directory color)
light_blue = "#5fafd7"    # 74 (nix shell)
blue = "#0087ff"          # 33
magenta = "#af5fff"       # 135
white = "#eeeeee"         # 255
foreground = "#bcbcbc"    # 250
foreground_gutter = "#6c6c6c"  # 242
comment = "#6c6c6c"       # 242 (frame/ornament color)
dark_gray = "#444444"     # 238 (background)
black = "#303030"         # 236
bg = "#303030"            # 236 (terminal background)
bg_highlight = "#444444"  # 238
bg_dark = "#1c1c1c"       # 234
segment_bg = "#444444"    # 238 (P10k background)
terminal_black = "#303030"
fg = "#bcbcbc"
fg_dark = "#6c6c6c"

# Fill module to create the extended line
[fill]
symbol = "─"
style = "fg:#6c6c6c"

# OS module - show OS icon
[os]
disabled = false
style = "fg:#eeeeee bg:#444444"
format = "[ $symbol]($style)"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Arch = "󰣇"
Debian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
NixOS = ""

# Username - only show on SSH
[username]
show_always = false
style_user = "fg:#00afff bg:#444444 bold"
style_root = "fg:#d70000 bg:#444444 bold"
format = "[$user]($style)"

# Hostname - only show on SSH
[hostname]
ssh_only = true
format = "[@$hostname ](fg:#00afff bg:#444444 bold)"
disabled = false

# Directory with proper spacing and separator
[directory]
style = "fg:#00afff bg:#444444 bold"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "../"
truncate_to_repo = false

# Git branch
[git_branch]
symbol = ""
style = "fg:#5fd700 bg:#444444"
format = "[](fg:#6c6c6c bg:#444444)[ $symbol $branch ]($style)"

# Git status - with file counts like P10k
[git_status]
format = "$ahead_behind$all_status"
conflicted = "~$count "
ahead = "[⇡$count ](fg:#5fd700 bg:#444444)"
behind = "[⇣$count ](fg:#5fd700 bg:#444444)"
diverged = "[⇡$ahead_count ⇣$behind_count ](fg:#5fd700 bg:#444444)"
up_to_date = ""
untracked = "[?$count ](fg:#d7af00 bg:#444444)"
stashed = "[*$count ](fg:#5fd700 bg:#444444)"
modified = "[!$count ](fg:#d7af00 bg:#444444)"
staged = "[+$count ](fg:#d7af00 bg:#444444)"
renamed = "[»$count ](fg:#d7af00 bg:#444444)"
deleted = "[✘$count ](fg:#d70000 bg:#444444)"

# Status - show success/error symbol with background
[status]
style = "fg:#5fd700 bg:#444444"
success_symbol = "[✔](fg:#5fd700 bg:#444444)"
format = "[ $symbol ]($style)"
map_symbol = false
disabled = true

# Command duration with background
[cmd_duration]
min_time = 10000
show_milliseconds = false
style = "fg:#d7af00 bg:#444444"
format = "[](fg:#6c6c6c bg:#444444)[ took $duration ]($style)"
disabled = true

# Nix shell with background
[nix_shell]
style = "fg:#5fafd7 bg:#444444 bold"
format = "[ $state  ]($style)"
impure_msg = "impure "
pure_msg = "pure "
unknown_msg = ""

# Time with background
[time]
disabled = false
time_format = "%H:%M:%S"
style = "fg:#bcbcbc bg:#444444"
format = "[](fg:#6c6c6c bg:#444444)[ $time  ]($style)"

# Line break
[line_break]
disabled = false

# Character - prompt symbol
[character]
disabled = false
success_symbol = "[❯](bold fg:#5fd700)"
error_symbol = "[❯](bold fg:#d70000)"
vimcmd_symbol = "[❮](bold fg:#5fd700)"
vimcmd_replace_one_symbol = "[❮](bold fg:#af5fff)"
vimcmd_replace_symbol = "[❮](bold fg:#af5fff)"
vimcmd_visual_symbol = "[❮](bold fg:#d7af00)"

[python]
symbol = ""
style = "fg:#d7af00 bg:#444444"
format = " [$symbol ($pyenv_prefix)($version)(\\($virtualenv\\)) ]($style)"
disabled = false

# Container/Environment tools with backgrounds
[docker_context]
symbol = ""
style = "fg:#00afff bg:#444444"
format = " [$symbol $context ]($style)"
disabled = false
