version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    environment:
      - RUNNER_SCOPE=${RUNNER_SCOPE:-repo}
      - REPO_URL=${REPO_URL}
      - ORG_NAME=${ORG_NAME}
      - LABELS=${LABELS:-docker,self-hosted,linux,x64}
      - EPHEMERAL=${EPHEMERAL:-true}
      - DISABLE_AUTO_UPDATE=true
      - ACCESS_TOKEN=${GITHUB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - github-runner-work:/home/runner/_work
    networks:
      - runner-network

volumes:
  github-runner-work:

networks:
  runner-network:
    driver: bridge