version: "3"

services:
  jellyfin:
    environment:
      - JELLYFIN_PublishedServerUrl=
      - TZ=America/Los_Angeles
    image: linuxserver/jellyfin:latest
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
      - target: 8920
        published: "8920"
        protocol: tcp
      - target: 7359
        published: "7359"
        protocol: udp
      - target: 1900
        published: "1900"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: ~/config/jellyfin
        target: /config
      - type: bind
        source: /mnt/titan/TVShows
        target: /data/tvshows
      - type: bind
        source: /mnt/titan/Movies
        target: /data/movies
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    privileged: false
    container_name: "jellyfin"

